pipeline {
    agent {
        label 'docker'    
    }
    
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'pwd'
                sh 'uname --all'
            }
        }
    }
}
